name: Build on push to master

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: raspi-space

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t discord-bot-typescript:latest .
